[project]
name = "distributed-key"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "colorama>=0.4.6",
    "paramiko>=2.11.0",
    "pyyaml>=6.0",
]
